version: "3.9"
services:
  app-backend:
    container_name: "app-backend"
    image: ""
    volumes:
      - ./data/app/:/app
    build:
      context: .
      dockerfile: .docker/Dockerfile
     env_file:
       - .env
    restart: unless-stopped
    networks:
      - app
networks:
  app:
    external: true
